name: Code Hygiene

on:
  pull_request:
    branches:
      - main

jobs:
  code-hygiene:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Formatting
        run: npm run check-format

      - name: Linting
        run: npm run check-lint

      - name: Build
        run: npm run build
