name: Create Release Tag

on:
  push:
    branches:
      - production

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Create Tag Name
        run: |
          GIT_TAG=$(date +v%Y.%m.%d-%H.%M.%S)-$(git log --format=%h -1)
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GIT_TAG }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      # # Create unique release tag
      # - uses: rickstaa/action-create-tag@v1
      #   name: Create Unique Tag
      #   id: 'tag_create_unique'
      #   with:
      #     tag: ${{ env.GIT_TAG }}
      #     tag_exists_error: true

      # # Create latest release tag
      # - uses: rickstaa/action-create-tag@v1
      #   name: Create Latest Tag
      #   id: 'tag_create_latest'
      #   with:
      #     tag: 'latest'
      #     force_push_tag: true
      #     message: 'Latest release'
