name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - test-action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment variable
      run: echo "Value of GCP_PROJECT_ID is $GCP_PROJECT_ID"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run clean-build

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy govuk-knowledge-graph-search \
            --source . \
            --region "europe-west2" \
            --tag CD-commit-`git rev-parse --short HEAD` \
            --project $GCP_PROJECT_ID
