name: My Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  myJob:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Only for PR merge
        run: echo "YES"
